name: 𝐙𝐄𝐙𝐄-𝐌𝐃_𝐕𝟓
services:
  - name: 𝐙𝐄𝐙𝐄-𝐌𝐃_𝐕𝟓-service
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
